Mini Bug and Wishlist Tracker



* Bug List
Untuk kesalahan / keanehan / sesuatu yang perlu diperbaiki dari fitur
yang sudah ada.

  + [ ] Deskripsi singkat. Ini contoh sebagai template.
    - Assignee : (Siapa yang garap)
    - Status : (Delayed, In-Progress, Done)
    - Solving Method :
      (Bagaimana menyelesaikan, pakai library apa)

  + [ ] Navigasi bagian kanan kurang terlihat untuk halaman ketiga
    - Assignee : -
    - Status : Delayed
    - Solving Method :
      Ubah menjadi lingkaran2 warna putih.

  + [X] Icon sosmed Twitter dan FB di halaman 3 tidak tampil JIKA dilihat secara online, offline keliatan.
    - Assignee : -
    - Status : Delayed
    - Solving Method :
      Tiba tiba bener sendiri

  + [X] Ukuran font h tidak dapat diubah.
    - Assignee : -
    - Status : Delayed
    - Solving Method :
      Mungkin ada library js yang meng-overwrite pengaturan ukuran font.
      Fixed: css style kita diubah posisinya ke paling bawah, biar ngeoverwrite css dari library.


* Wish List
Untuk fitur yang masih belum diimplementasi.

  + [ ] Deskripsi singkat. Ini contoh sebagai template.
    - Assignee : (Siapa yang garap)
    - Status : (Delayed, In-Progress, Done)
    - Solving Method :
      (Bagaimana menyelesaikan, pakai library apa, dll)

  + [X] Ganti dengan Official Font : OpenSans
    - Assignee : Abdillah
    - Status : Done
    - Solving Method :
      Untuk sementara dengan font offline, nantinya dengan font di http://www.google.com/fonts.

  + [X] Autoswitch halaman kedua kurang interaktif tanpa sliderbar (kayak slider di website official 2014)
    - Assignee : Abdillah
    - Status : Done - Beta
    - Detail :
      Di slide kedua, setelah 10 detik, tiba-tiba saja slide berganti tanpa tanda2.
      Nah, gimana caranya nambahin tanda-tanda. Misalnya dengan cara di bawah.
    - Solving Method :
      Tambahkan timer slidebar (kayak progressbar) dengan library 'NProgress'.
