$(document).ready(function() {
    $('#content-isi').hide();
    $('#download-isi').hide();
    $('#peraturan').click(function(){
        $('#content-isi').hide();
        $('#download-isi').hide();
        $('#peraturan-isi').show();
        $('#content').removeClass('lomba-menu-click');
        $('#download').removeClass('lomba-menu-click');
        $('#peraturan').addClass('lomba-menu-click');
    });
    $('#content').click(function(){
        $('#peraturan-isi').hide();
        $('#download-isi').hide();
        $('#content-isi').show();
        $('#download').removeClass('lomba-menu-click');
        $('#peraturan').removeClass('lomba-menu-click');
        $('#content').addClass('lomba-menu-click');
    });
    $('#download').click(function(){
        $('#content-isi').hide();
        $('#peraturan-isi').hide();
        $('#download-isi').show();
        $('#peraturan').removeClass('lomba-menu-click');
        $('#content').removeClass('lomba-menu-click');
        $('#download').addClass('lomba-menu-click');
    });
});